/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsIndexRouteImport } from './routes/apps.index'
import { Route as DeploymentsDeployIdRouteImport } from './routes/deployments.$deployId'
import { Route as AppsNewRouteImport } from './routes/apps.new'
import { Route as AppsAppIdRouteImport } from './routes/apps.$appId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsDeployIdRoute = DeploymentsDeployIdRouteImport.update({
  id: '/deployments/$deployId',
  path: '/deployments/$deployId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsNewRoute = AppsNewRouteImport.update({
  id: '/apps/new',
  path: '/apps/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppIdRoute = AppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/apps/new': typeof AppsNewRoute
  '/deployments/$deployId': typeof DeploymentsDeployIdRoute
  '/apps/': typeof AppsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/apps/new': typeof AppsNewRoute
  '/deployments/$deployId': typeof DeploymentsDeployIdRoute
  '/apps': typeof AppsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/apps/new': typeof AppsNewRoute
  '/deployments/$deployId': typeof DeploymentsDeployIdRoute
  '/apps/': typeof AppsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/apps/$appId'
    | '/apps/new'
    | '/deployments/$deployId'
    | '/apps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/apps/$appId'
    | '/apps/new'
    | '/deployments/$deployId'
    | '/apps'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/apps/$appId'
    | '/apps/new'
    | '/deployments/$deployId'
    | '/apps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  AppsAppIdRoute: typeof AppsAppIdRoute
  AppsNewRoute: typeof AppsNewRoute
  DeploymentsDeployIdRoute: typeof DeploymentsDeployIdRoute
  AppsIndexRoute: typeof AppsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/$deployId': {
      id: '/deployments/$deployId'
      path: '/deployments/$deployId'
      fullPath: '/deployments/$deployId'
      preLoaderRoute: typeof DeploymentsDeployIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/new': {
      id: '/apps/new'
      path: '/apps/new'
      fullPath: '/apps/new'
      preLoaderRoute: typeof AppsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$appId': {
      id: '/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  AppsAppIdRoute: AppsAppIdRoute,
  AppsNewRoute: AppsNewRoute,
  DeploymentsDeployIdRoute: DeploymentsDeployIdRoute,
  AppsIndexRoute: AppsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
