// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"
)

type App struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	RepoFullName   string    `json:"repo_full_name"`
	InstallationID int64     `json:"installation_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type Deployment struct {
	ID            string     `json:"id"`
	AppID         string     `json:"app_id"`
	EnvironmentID *string    `json:"environment_id"`
	CommitSha     string     `json:"commit_sha"`
	CommitMessage string     `json:"commit_message"`
	ImageTag      *string    `json:"image_tag"`
	Status        string     `json:"status"`
	NomadJobHcl   *string    `json:"nomad_job_hcl"`
	EnvSnapshot   *string    `json:"env_snapshot"`
	Error         *string    `json:"error"`
	StartedAt     time.Time  `json:"started_at"`
	FinishedAt    *time.Time `json:"finished_at"`
}

type DeploymentLog struct {
	ID           int64     `json:"id"`
	DeploymentID string    `json:"deployment_id"`
	Phase        string    `json:"phase"`
	Content      string    `json:"content"`
	CreatedAt    time.Time `json:"created_at"`
}

type Environment struct {
	ID            string    `json:"id"`
	AppID         string    `json:"app_id"`
	Name          string    `json:"name"`
	AgePublicKey  string    `json:"age_public_key"`
	AgePrivateKey string    `json:"age_private_key"`
	CreatedAt     time.Time `json:"created_at"`
}

type GithubApp struct {
	ID            int64     `json:"id"`
	AppID         int64     `json:"app_id"`
	Slug          string    `json:"slug"`
	Name          string    `json:"name"`
	ClientID      string    `json:"client_id"`
	ClientSecret  string    `json:"client_secret"`
	WebhookSecret string    `json:"webhook_secret"`
	PrivateKey    string    `json:"private_key"`
	HtmlUrl       string    `json:"html_url"`
	CreatedAt     time.Time `json:"created_at"`
}

type GithubInstallation struct {
	ID           int64     `json:"id"`
	AccountLogin string    `json:"account_login"`
	AccountType  string    `json:"account_type"`
	CreatedAt    time.Time `json:"created_at"`
}
