// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
)

const createApp = `-- name: CreateApp :exec
INSERT INTO app (id, name, repo_full_name, installation_id) VALUES (?, ?, ?, ?)
`

type CreateAppParams struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	RepoFullName   string `json:"repo_full_name"`
	InstallationID int64  `json:"installation_id"`
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) error {
	_, err := q.db.ExecContext(ctx, createApp,
		arg.ID,
		arg.Name,
		arg.RepoFullName,
		arg.InstallationID,
	)
	return err
}

const createDeployment = `-- name: CreateDeployment :exec
INSERT INTO deployment (id, app_id, environment_id, commit_sha, commit_message, status)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateDeploymentParams struct {
	ID            string  `json:"id"`
	AppID         string  `json:"app_id"`
	EnvironmentID *string `json:"environment_id"`
	CommitSha     string  `json:"commit_sha"`
	CommitMessage string  `json:"commit_message"`
	Status        string  `json:"status"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, createDeployment,
		arg.ID,
		arg.AppID,
		arg.EnvironmentID,
		arg.CommitSha,
		arg.CommitMessage,
		arg.Status,
	)
	return err
}

const createEnvironment = `-- name: CreateEnvironment :exec
INSERT INTO environment (id, app_id, name, age_public_key, age_private_key)
VALUES (?, ?, ?, ?, ?)
`

type CreateEnvironmentParams struct {
	ID            string `json:"id"`
	AppID         string `json:"app_id"`
	Name          string `json:"name"`
	AgePublicKey  string `json:"age_public_key"`
	AgePrivateKey string `json:"age_private_key"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) error {
	_, err := q.db.ExecContext(ctx, createEnvironment,
		arg.ID,
		arg.AppID,
		arg.Name,
		arg.AgePublicKey,
		arg.AgePrivateKey,
	)
	return err
}

const finishDeployment = `-- name: FinishDeployment :exec
UPDATE deployment SET status = ?, finished_at = CURRENT_TIMESTAMP WHERE id = ?
`

type FinishDeploymentParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) FinishDeployment(ctx context.Context, arg FinishDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, finishDeployment, arg.Status, arg.ID)
	return err
}

const getApp = `-- name: GetApp :one
SELECT id, name, repo_full_name, installation_id, created_at FROM app WHERE id = ?
`

func (q *Queries) GetApp(ctx context.Context, id string) (App, error) {
	row := q.db.QueryRowContext(ctx, getApp, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoFullName,
		&i.InstallationID,
		&i.CreatedAt,
	)
	return i, err
}

const getAppByName = `-- name: GetAppByName :one
SELECT id, name, repo_full_name, installation_id, created_at FROM app WHERE name = ?
`

func (q *Queries) GetAppByName(ctx context.Context, name string) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByName, name)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoFullName,
		&i.InstallationID,
		&i.CreatedAt,
	)
	return i, err
}

const getAppByRepo = `-- name: GetAppByRepo :one
SELECT id, name, repo_full_name, installation_id, created_at FROM app WHERE repo_full_name = ?
`

func (q *Queries) GetAppByRepo(ctx context.Context, repoFullName string) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByRepo, repoFullName)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoFullName,
		&i.InstallationID,
		&i.CreatedAt,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, app_id, environment_id, commit_sha, commit_message, image_tag, status, nomad_job_hcl, env_snapshot, error, started_at, finished_at FROM deployment WHERE id = ?
`

func (q *Queries) GetDeployment(ctx context.Context, id string) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EnvironmentID,
		&i.CommitSha,
		&i.CommitMessage,
		&i.ImageTag,
		&i.Status,
		&i.NomadJobHcl,
		&i.EnvSnapshot,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getDeploymentLog = `-- name: GetDeploymentLog :one
SELECT id, deployment_id, phase, content, created_at FROM deployment_log WHERE deployment_id = ? AND phase = ?
`

type GetDeploymentLogParams struct {
	DeploymentID string `json:"deployment_id"`
	Phase        string `json:"phase"`
}

func (q *Queries) GetDeploymentLog(ctx context.Context, arg GetDeploymentLogParams) (DeploymentLog, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentLog, arg.DeploymentID, arg.Phase)
	var i DeploymentLog
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.Phase,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, app_id, name, age_public_key, age_private_key, created_at FROM environment WHERE app_id = ? AND name = ?
`

type GetEnvironmentParams struct {
	AppID string `json:"app_id"`
	Name  string `json:"name"`
}

func (q *Queries) GetEnvironment(ctx context.Context, arg GetEnvironmentParams) (Environment, error) {
	row := q.db.QueryRowContext(ctx, getEnvironment, arg.AppID, arg.Name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.AgePublicKey,
		&i.AgePrivateKey,
		&i.CreatedAt,
	)
	return i, err
}

const getEnvironmentByID = `-- name: GetEnvironmentByID :one
SELECT id, app_id, name, age_public_key, age_private_key, created_at FROM environment WHERE id = ?
`

func (q *Queries) GetEnvironmentByID(ctx context.Context, id string) (Environment, error) {
	row := q.db.QueryRowContext(ctx, getEnvironmentByID, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.AgePublicKey,
		&i.AgePrivateKey,
		&i.CreatedAt,
	)
	return i, err
}

const getGitHubApp = `-- name: GetGitHubApp :one
SELECT id, app_id, slug, name, client_id, client_secret, webhook_secret, private_key, html_url, created_at FROM github_app WHERE id = 1
`

func (q *Queries) GetGitHubApp(ctx context.Context) (GithubApp, error) {
	row := q.db.QueryRowContext(ctx, getGitHubApp)
	var i GithubApp
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Slug,
		&i.Name,
		&i.ClientID,
		&i.ClientSecret,
		&i.WebhookSecret,
		&i.PrivateKey,
		&i.HtmlUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listApps = `-- name: ListApps :many
SELECT id, name, repo_full_name, installation_id, created_at FROM app ORDER BY name
`

func (q *Queries) ListApps(ctx context.Context) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoFullName,
			&i.InstallationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployments = `-- name: ListDeployments :many
SELECT id, app_id, environment_id, commit_sha, commit_message, image_tag, status, nomad_job_hcl, env_snapshot, error, started_at, finished_at FROM deployment WHERE app_id = ? ORDER BY started_at DESC LIMIT ?
`

type ListDeploymentsParams struct {
	AppID string `json:"app_id"`
	Limit int64  `json:"limit"`
}

func (q *Queries) ListDeployments(ctx context.Context, arg ListDeploymentsParams) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeployments, arg.AppID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.EnvironmentID,
			&i.CommitSha,
			&i.CommitMessage,
			&i.ImageTag,
			&i.Status,
			&i.NomadJobHcl,
			&i.EnvSnapshot,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, app_id, name, age_public_key, age_private_key, created_at FROM environment WHERE app_id = ? ORDER BY name
`

func (q *Queries) ListEnvironments(ctx context.Context, appID string) ([]Environment, error) {
	rows, err := q.db.QueryContext(ctx, listEnvironments, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.AgePublicKey,
			&i.AgePrivateKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallations = `-- name: ListInstallations :many
SELECT id, account_login, account_type, created_at FROM github_installation ORDER BY account_login
`

func (q *Queries) ListInstallations(ctx context.Context) ([]GithubInstallation, error) {
	rows, err := q.db.QueryContext(ctx, listInstallations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubInstallation{}
	for rows.Next() {
		var i GithubInstallation
		if err := rows.Scan(
			&i.ID,
			&i.AccountLogin,
			&i.AccountType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentArtifact = `-- name: UpdateDeploymentArtifact :exec
UPDATE deployment SET image_tag = ?, nomad_job_hcl = ?, env_snapshot = ? WHERE id = ?
`

type UpdateDeploymentArtifactParams struct {
	ImageTag    *string `json:"image_tag"`
	NomadJobHcl *string `json:"nomad_job_hcl"`
	EnvSnapshot *string `json:"env_snapshot"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateDeploymentArtifact(ctx context.Context, arg UpdateDeploymentArtifactParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentArtifact,
		arg.ImageTag,
		arg.NomadJobHcl,
		arg.EnvSnapshot,
		arg.ID,
	)
	return err
}

const updateDeploymentEnvironment = `-- name: UpdateDeploymentEnvironment :exec
UPDATE deployment SET environment_id = ? WHERE id = ?
`

type UpdateDeploymentEnvironmentParams struct {
	EnvironmentID *string `json:"environment_id"`
	ID            string  `json:"id"`
}

func (q *Queries) UpdateDeploymentEnvironment(ctx context.Context, arg UpdateDeploymentEnvironmentParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentEnvironment, arg.EnvironmentID, arg.ID)
	return err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployment SET status = ?, error = ? WHERE id = ?
`

type UpdateDeploymentStatusParams struct {
	Status string  `json:"status"`
	Error  *string `json:"error"`
	ID     string  `json:"id"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentStatus, arg.Status, arg.Error, arg.ID)
	return err
}

const upsertDeploymentLog = `-- name: UpsertDeploymentLog :exec
INSERT INTO deployment_log (deployment_id, phase, content)
VALUES (?, ?, ?)
ON CONFLICT(deployment_id, phase) DO UPDATE SET content = excluded.content
`

type UpsertDeploymentLogParams struct {
	DeploymentID string `json:"deployment_id"`
	Phase        string `json:"phase"`
	Content      string `json:"content"`
}

func (q *Queries) UpsertDeploymentLog(ctx context.Context, arg UpsertDeploymentLogParams) error {
	_, err := q.db.ExecContext(ctx, upsertDeploymentLog, arg.DeploymentID, arg.Phase, arg.Content)
	return err
}

const upsertGitHubApp = `-- name: UpsertGitHubApp :exec
INSERT INTO github_app (id, app_id, slug, name, client_id, client_secret, webhook_secret, private_key, html_url)
VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    app_id = excluded.app_id,
    slug = excluded.slug,
    name = excluded.name,
    client_id = excluded.client_id,
    client_secret = excluded.client_secret,
    webhook_secret = excluded.webhook_secret,
    private_key = excluded.private_key,
    html_url = excluded.html_url
`

type UpsertGitHubAppParams struct {
	AppID         int64  `json:"app_id"`
	Slug          string `json:"slug"`
	Name          string `json:"name"`
	ClientID      string `json:"client_id"`
	ClientSecret  string `json:"client_secret"`
	WebhookSecret string `json:"webhook_secret"`
	PrivateKey    string `json:"private_key"`
	HtmlUrl       string `json:"html_url"`
}

func (q *Queries) UpsertGitHubApp(ctx context.Context, arg UpsertGitHubAppParams) error {
	_, err := q.db.ExecContext(ctx, upsertGitHubApp,
		arg.AppID,
		arg.Slug,
		arg.Name,
		arg.ClientID,
		arg.ClientSecret,
		arg.WebhookSecret,
		arg.PrivateKey,
		arg.HtmlUrl,
	)
	return err
}

const upsertInstallation = `-- name: UpsertInstallation :exec
INSERT INTO github_installation (id, account_login, account_type)
VALUES (?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    account_login = excluded.account_login,
    account_type = excluded.account_type
`

type UpsertInstallationParams struct {
	ID           int64  `json:"id"`
	AccountLogin string `json:"account_login"`
	AccountType  string `json:"account_type"`
}

func (q *Queries) UpsertInstallation(ctx context.Context, arg UpsertInstallationParams) error {
	_, err := q.db.ExecContext(ctx, upsertInstallation, arg.ID, arg.AccountLogin, arg.AccountType)
	return err
}
