// Code generated by sqlc. DO NOT EDIT.

package dbgen

import (
	"context"
	"database/sql"
)

type Queries struct {
	db *sql.DB
}

func New(db *sql.DB) *Queries {
	return &Queries{db: db}
}

// ensure context is imported
var _ context.Context
