// Code generated by sqlc. DO NOT EDIT.

package dbgen

import "time"

type Node struct {
	ID                 string     `json:"id"`
	Name               string     `json:"name"`
	PublicIP           string     `json:"public_ip"`
	SshUser            string     `json:"ssh_user"`
	SshKeyPath         string     `json:"ssh_key_path"`
	Tags               string     `json:"tags"` // JSON array
	IsDarksidePaasNode int64      `json:"is_darkside_paas_node"`
	Status             string     `json:"status"`
	NomadNodeID        *string    `json:"nomad_node_id"`
	CreatedAt          time.Time  `json:"created_at"`
}

type ClusterConfig struct {
	ID         int64     `json:"id"`
	NodeID     string    `json:"node_id"`
	NomadHcl   string    `json:"nomad_hcl"`
	ConsulHcl  string    `json:"consul_hcl"`
	TraefikYml string    `json:"traefik_yml"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Job struct {
	ID         string     `json:"id"`
	Type       string     `json:"type"`
	Status     string     `json:"status"`
	Payload    string     `json:"payload"`
	Output     string     `json:"output"`
	CreatedAt  time.Time  `json:"created_at"`
	StartedAt  *time.Time `json:"started_at"`
	FinishedAt *time.Time `json:"finished_at"`
}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}
