// Code generated by sqlc. DO NOT EDIT.

package dbgen

import (
	"context"
	"time"
)

// ── Nodes ─────────────────────────────────────────────────────────────────────

const listNodes = `SELECT id, name, public_ip, ssh_user, ssh_key_path, tags, is_darkside_paas_node, status, nomad_node_id, created_at FROM nodes ORDER BY created_at`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(&i.ID, &i.Name, &i.PublicIP, &i.SshUser, &i.SshKeyPath, &i.Tags, &i.IsDarksidePaasNode, &i.Status, &i.NomadNodeID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getNode = `SELECT id, name, public_ip, ssh_user, ssh_key_path, tags, is_darkside_paas_node, status, nomad_node_id, created_at FROM nodes WHERE id = ?`

func (q *Queries) GetNode(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNode, id)
	var i Node
	err := row.Scan(&i.ID, &i.Name, &i.PublicIP, &i.SshUser, &i.SshKeyPath, &i.Tags, &i.IsDarksidePaasNode, &i.Status, &i.NomadNodeID, &i.CreatedAt)
	return i, err
}

const getNodeByName = `SELECT id, name, public_ip, ssh_user, ssh_key_path, tags, is_darkside_paas_node, status, nomad_node_id, created_at FROM nodes WHERE name = ?`

func (q *Queries) GetNodeByName(ctx context.Context, name string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByName, name)
	var i Node
	err := row.Scan(&i.ID, &i.Name, &i.PublicIP, &i.SshUser, &i.SshKeyPath, &i.Tags, &i.IsDarksidePaasNode, &i.Status, &i.NomadNodeID, &i.CreatedAt)
	return i, err
}

const createNode = `INSERT INTO nodes (id, name, public_ip, ssh_user, ssh_key_path, tags, is_darkside_paas_node) VALUES (?, ?, ?, ?, ?, ?, ?)`

type CreateNodeParams struct {
	ID                 string `json:"id"`
	Name               string `json:"name"`
	PublicIP           string `json:"public_ip"`
	SshUser            string `json:"ssh_user"`
	SshKeyPath         string `json:"ssh_key_path"`
	Tags               string `json:"tags"`
	IsDarksidePaasNode int64  `json:"is_darkside_paas_node"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) error {
	_, err := q.db.ExecContext(ctx, createNode, arg.ID, arg.Name, arg.PublicIP, arg.SshUser, arg.SshKeyPath, arg.Tags, arg.IsDarksidePaasNode)
	return err
}

const updateNodeStatus = `UPDATE nodes SET status = ?, nomad_node_id = COALESCE(?, nomad_node_id) WHERE id = ?`

type UpdateNodeStatusParams struct {
	Status      string  `json:"status"`
	NomadNodeID *string `json:"nomad_node_id"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateNodeStatus(ctx context.Context, arg UpdateNodeStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateNodeStatus, arg.Status, arg.NomadNodeID, arg.ID)
	return err
}

const setPaasNode = `UPDATE nodes SET is_darkside_paas_node = (id = ?)`

func (q *Queries) SetPaasNode(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setPaasNode, id)
	return err
}

const deleteNode = `DELETE FROM nodes WHERE id = ?`

func (q *Queries) DeleteNode(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNode, id)
	return err
}

const countNodes = `SELECT COUNT(*) FROM nodes`

func (q *Queries) CountNodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNodes)
	var count int64
	return count, row.Scan(&count)
}

// ── Cluster configs ───────────────────────────────────────────────────────────

const upsertClusterConfig = `INSERT INTO cluster_configs (node_id, nomad_hcl, consul_hcl, traefik_yml, updated_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(node_id) DO UPDATE SET nomad_hcl = excluded.nomad_hcl, consul_hcl = excluded.consul_hcl, traefik_yml = excluded.traefik_yml, updated_at = excluded.updated_at`

type UpsertClusterConfigParams struct {
	NodeID     string `json:"node_id"`
	NomadHcl   string `json:"nomad_hcl"`
	ConsulHcl  string `json:"consul_hcl"`
	TraefikYml string `json:"traefik_yml"`
}

func (q *Queries) UpsertClusterConfig(ctx context.Context, arg UpsertClusterConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertClusterConfig, arg.NodeID, arg.NomadHcl, arg.ConsulHcl, arg.TraefikYml)
	return err
}

const getClusterConfig = `SELECT id, node_id, nomad_hcl, consul_hcl, traefik_yml, updated_at FROM cluster_configs WHERE node_id = ?`

func (q *Queries) GetClusterConfig(ctx context.Context, nodeID string) (ClusterConfig, error) {
	row := q.db.QueryRowContext(ctx, getClusterConfig, nodeID)
	var i ClusterConfig
	err := row.Scan(&i.ID, &i.NodeID, &i.NomadHcl, &i.ConsulHcl, &i.TraefikYml, &i.UpdatedAt)
	return i, err
}

// ── Jobs ──────────────────────────────────────────────────────────────────────

const listJobs = `SELECT id, type, status, payload, output, created_at, started_at, finished_at FROM jobs ORDER BY created_at DESC LIMIT ?`

func (q *Queries) ListJobs(ctx context.Context, limit int64) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(&i.ID, &i.Type, &i.Status, &i.Payload, &i.Output, &i.CreatedAt, &i.StartedAt, &i.FinishedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getJob = `SELECT id, type, status, payload, output, created_at, started_at, finished_at FROM jobs WHERE id = ?`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(&i.ID, &i.Type, &i.Status, &i.Payload, &i.Output, &i.CreatedAt, &i.StartedAt, &i.FinishedAt)
	return i, err
}

const getPendingJob = `SELECT id, type, status, payload, output, created_at, started_at, finished_at FROM jobs WHERE status = 'pending' ORDER BY created_at LIMIT 1`

func (q *Queries) GetPendingJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRowContext(ctx, getPendingJob)
	var i Job
	err := row.Scan(&i.ID, &i.Type, &i.Status, &i.Payload, &i.Output, &i.CreatedAt, &i.StartedAt, &i.FinishedAt)
	return i, err
}

const createJob = `INSERT INTO jobs (id, type, status, payload) VALUES (?, ?, 'pending', ?)`

type CreateJobParams struct {
	ID      string `json:"id"`
	Type    string `json:"type"`
	Payload string `json:"payload"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.ExecContext(ctx, createJob, arg.ID, arg.Type, arg.Payload)
	return err
}

const startJob = `UPDATE jobs SET status = 'running', started_at = CURRENT_TIMESTAMP WHERE id = ?`

func (q *Queries) StartJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, startJob, id)
	return err
}

const appendJobOutput = `UPDATE jobs SET output = output || ? WHERE id = ?`

func (q *Queries) AppendJobOutput(ctx context.Context, output, id string) error {
	_, err := q.db.ExecContext(ctx, appendJobOutput, output, id)
	return err
}

const finishJob = `UPDATE jobs SET status = ?, finished_at = CURRENT_TIMESTAMP WHERE id = ?`

type FinishJobParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.ExecContext(ctx, finishJob, arg.Status, arg.ID)
	return err
}

// ── Settings ──────────────────────────────────────────────────────────────────

const getSetting = `SELECT value FROM settings WHERE key = ?`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	return value, row.Scan(&value)
}

const setSetting = `INSERT INTO settings (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value`

type SetSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.db.ExecContext(ctx, setSetting, arg.Key, arg.Value)
	return err
}

// suppress unused import
var _ = time.Now
