// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"
)

type App struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	RepoFullName   string    `json:"repo_full_name"`
	InstallationID int64     `json:"installation_id"`
	CreatedAt      time.Time `json:"created_at"`
	Branch         string    `json:"branch"`
	EnvFile        string    `json:"env_file"`
	AgePublicKey   string    `json:"age_public_key"`
	AgePrivateKey  string    `json:"age_private_key"`
	AgeKeyID       string    `json:"age_key_id"`
}

type Deployment struct {
	ID             string     `json:"id"`
	AppID          string     `json:"app_id"`
	CommitSha      string     `json:"commit_sha"`
	CommitMessage  string     `json:"commit_message"`
	ImageTag       *string    `json:"image_tag"`
	Status         string     `json:"status"`
	NomadJobHcl    *string    `json:"nomad_job_hcl"`
	EnvSnapshot    *string    `json:"env_snapshot"`
	Error          *string    `json:"error"`
	StartedAt      time.Time  `json:"started_at"`
	FinishedAt     *time.Time `json:"finished_at"`
	TriggerType    string     `json:"trigger_type"`
	TriggerBranch  *string    `json:"trigger_branch"`
	BuildJobHcl    *string    `json:"build_job_hcl"`
	PreHookHcl     *string    `json:"pre_hook_hcl"`
	PostHookHcl    *string    `json:"post_hook_hcl"`
}

type DeploymentLog struct {
	ID           int64     `json:"id"`
	DeploymentID string    `json:"deployment_id"`
	Phase        string    `json:"phase"`
	Content      string    `json:"content"`
	CreatedAt    time.Time `json:"created_at"`
}

type GithubApp struct {
	ID            int64     `json:"id"`
	AppID         int64     `json:"app_id"`
	Slug          string    `json:"slug"`
	Name          string    `json:"name"`
	ClientID      string    `json:"client_id"`
	ClientSecret  string    `json:"client_secret"`
	WebhookSecret string    `json:"webhook_secret"`
	PrivateKey    string    `json:"private_key"`
	HtmlUrl       string    `json:"html_url"`
	CreatedAt     time.Time `json:"created_at"`
}

type GithubInstallation struct {
	ID           int64     `json:"id"`
	AccountLogin string    `json:"account_login"`
	AccountType  string    `json:"account_type"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID         int64     `json:"id"`
	GithubID   int64     `json:"github_id"`
	Login      string    `json:"login"`
	Email      *string   `json:"email"`
	IsAdmin    int64     `json:"is_admin"`
	Whitelisted int64    `json:"whitelisted"`
	CreatedAt  time.Time `json:"created_at"`
}

type Session struct {
	Token     string    `json:"token"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type SessionWithUser struct {
	Token       string    `json:"token"`
	UserID      int64     `json:"user_id"`
	CreatedAt   time.Time `json:"created_at"`
	ExpiresAt   time.Time `json:"expires_at"`
	Uid         int64     `json:"uid"`
	GithubID    int64     `json:"github_id"`
	Login       string    `json:"login"`
	Email       *string   `json:"email"`
	IsAdmin     int64     `json:"is_admin"`
	Whitelisted int64     `json:"whitelisted"`
}
