// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"
)

// ── GitHub App ───────────────────────────────────────────────────────────────

const getGitHubApp = `SELECT id, app_id, slug, name, client_id, client_secret, webhook_secret, private_key, html_url, created_at FROM github_app WHERE id = 1`

func (q *Queries) GetGitHubApp(ctx context.Context) (GithubApp, error) {
	row := q.db.QueryRowContext(ctx, getGitHubApp)
	var i GithubApp
	err := row.Scan(&i.ID, &i.AppID, &i.Slug, &i.Name, &i.ClientID, &i.ClientSecret, &i.WebhookSecret, &i.PrivateKey, &i.HtmlUrl, &i.CreatedAt)
	return i, err
}

const upsertGitHubApp = `INSERT INTO github_app (id, app_id, slug, name, client_id, client_secret, webhook_secret, private_key, html_url)
VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    app_id = excluded.app_id, slug = excluded.slug, name = excluded.name,
    client_id = excluded.client_id, client_secret = excluded.client_secret,
    webhook_secret = excluded.webhook_secret, private_key = excluded.private_key,
    html_url = excluded.html_url`

type UpsertGitHubAppParams struct {
	AppID         int64  `json:"app_id"`
	Slug          string `json:"slug"`
	Name          string `json:"name"`
	ClientID      string `json:"client_id"`
	ClientSecret  string `json:"client_secret"`
	WebhookSecret string `json:"webhook_secret"`
	PrivateKey    string `json:"private_key"`
	HtmlUrl       string `json:"html_url"`
}

func (q *Queries) UpsertGitHubApp(ctx context.Context, arg UpsertGitHubAppParams) error {
	_, err := q.db.ExecContext(ctx, upsertGitHubApp, arg.AppID, arg.Slug, arg.Name, arg.ClientID, arg.ClientSecret, arg.WebhookSecret, arg.PrivateKey, arg.HtmlUrl)
	return err
}

// ── Installations ────────────────────────────────────────────────────────────

const listInstallations = `SELECT id, account_login, account_type, created_at FROM github_installation ORDER BY account_login`

func (q *Queries) ListInstallations(ctx context.Context) ([]GithubInstallation, error) {
	rows, err := q.db.QueryContext(ctx, listInstallations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubInstallation{}
	for rows.Next() {
		var i GithubInstallation
		if err := rows.Scan(&i.ID, &i.AccountLogin, &i.AccountType, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const upsertInstallation = `INSERT INTO github_installation (id, account_login, account_type)
VALUES (?, ?, ?)
ON CONFLICT(id) DO UPDATE SET account_login = excluded.account_login, account_type = excluded.account_type`

type UpsertInstallationParams struct {
	ID           int64  `json:"id"`
	AccountLogin string `json:"account_login"`
	AccountType  string `json:"account_type"`
}

func (q *Queries) UpsertInstallation(ctx context.Context, arg UpsertInstallationParams) error {
	_, err := q.db.ExecContext(ctx, upsertInstallation, arg.ID, arg.AccountLogin, arg.AccountType)
	return err
}

// ── Apps ─────────────────────────────────────────────────────────────────────

const listApps = `SELECT id, name, repo_full_name, installation_id, created_at, branch, env_file, age_public_key, age_private_key, age_key_id FROM app ORDER BY name`

func (q *Queries) ListApps(ctx context.Context) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(&i.ID, &i.Name, &i.RepoFullName, &i.InstallationID, &i.CreatedAt, &i.Branch, &i.EnvFile, &i.AgePublicKey, &i.AgePrivateKey, &i.AgeKeyID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getApp = `SELECT id, name, repo_full_name, installation_id, created_at, branch, env_file, age_public_key, age_private_key, age_key_id FROM app WHERE id = ?`

func (q *Queries) GetApp(ctx context.Context, id string) (App, error) {
	row := q.db.QueryRowContext(ctx, getApp, id)
	var i App
	err := row.Scan(&i.ID, &i.Name, &i.RepoFullName, &i.InstallationID, &i.CreatedAt, &i.Branch, &i.EnvFile, &i.AgePublicKey, &i.AgePrivateKey, &i.AgeKeyID)
	return i, err
}

const getAppByName = `SELECT id, name, repo_full_name, installation_id, created_at, branch, env_file, age_public_key, age_private_key, age_key_id FROM app WHERE name = ?`

func (q *Queries) GetAppByName(ctx context.Context, name string) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByName, name)
	var i App
	err := row.Scan(&i.ID, &i.Name, &i.RepoFullName, &i.InstallationID, &i.CreatedAt, &i.Branch, &i.EnvFile, &i.AgePublicKey, &i.AgePrivateKey, &i.AgeKeyID)
	return i, err
}

const getAppByRepo = `SELECT id, name, repo_full_name, installation_id, created_at, branch, env_file, age_public_key, age_private_key, age_key_id FROM app WHERE repo_full_name = ?`

func (q *Queries) GetAppByRepo(ctx context.Context, repoFullName string) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByRepo, repoFullName)
	var i App
	err := row.Scan(&i.ID, &i.Name, &i.RepoFullName, &i.InstallationID, &i.CreatedAt, &i.Branch, &i.EnvFile, &i.AgePublicKey, &i.AgePrivateKey, &i.AgeKeyID)
	return i, err
}

const createApp = `INSERT INTO app (id, name, repo_full_name, installation_id, branch, env_file, age_public_key, age_private_key, age_key_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`

type CreateAppParams struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	RepoFullName   string `json:"repo_full_name"`
	InstallationID int64  `json:"installation_id"`
	Branch         string `json:"branch"`
	EnvFile        string `json:"env_file"`
	AgePublicKey   string `json:"age_public_key"`
	AgePrivateKey  string `json:"age_private_key"`
	AgeKeyID       string `json:"age_key_id"`
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) error {
	_, err := q.db.ExecContext(ctx, createApp, arg.ID, arg.Name, arg.RepoFullName, arg.InstallationID, arg.Branch, arg.EnvFile, arg.AgePublicKey, arg.AgePrivateKey, arg.AgeKeyID)
	return err
}

const updateAppAgeKey = `UPDATE app SET age_public_key = ?, age_private_key = ?, age_key_id = ? WHERE id = ?`

type UpdateAppAgeKeyParams struct {
	AgePublicKey  string `json:"age_public_key"`
	AgePrivateKey string `json:"age_private_key"`
	AgeKeyID      string `json:"age_key_id"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateAppAgeKey(ctx context.Context, arg UpdateAppAgeKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateAppAgeKey, arg.AgePublicKey, arg.AgePrivateKey, arg.AgeKeyID, arg.ID)
	return err
}

// ── Deployments ──────────────────────────────────────────────────────────────

const listDeployments = `SELECT id, app_id, commit_sha, commit_message, image_tag, status, nomad_job_hcl, env_snapshot, error, started_at, finished_at, trigger_type, trigger_branch, build_job_hcl, pre_hook_hcl, post_hook_hcl FROM deployment WHERE app_id = ? ORDER BY started_at DESC LIMIT ?`

type ListDeploymentsParams struct {
	AppID string `json:"app_id"`
	Limit int64  `json:"limit"`
}

func (q *Queries) ListDeployments(ctx context.Context, arg ListDeploymentsParams) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeployments, arg.AppID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(&i.ID, &i.AppID, &i.CommitSha, &i.CommitMessage, &i.ImageTag, &i.Status, &i.NomadJobHcl, &i.EnvSnapshot, &i.Error, &i.StartedAt, &i.FinishedAt, &i.TriggerType, &i.TriggerBranch, &i.BuildJobHcl, &i.PreHookHcl, &i.PostHookHcl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getDeployment = `SELECT id, app_id, commit_sha, commit_message, image_tag, status, nomad_job_hcl, env_snapshot, error, started_at, finished_at, trigger_type, trigger_branch, build_job_hcl, pre_hook_hcl, post_hook_hcl FROM deployment WHERE id = ?`

func (q *Queries) GetDeployment(ctx context.Context, id string) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(&i.ID, &i.AppID, &i.CommitSha, &i.CommitMessage, &i.ImageTag, &i.Status, &i.NomadJobHcl, &i.EnvSnapshot, &i.Error, &i.StartedAt, &i.FinishedAt, &i.TriggerType, &i.TriggerBranch, &i.BuildJobHcl, &i.PreHookHcl, &i.PostHookHcl)
	return i, err
}

const createDeployment = `INSERT INTO deployment (id, app_id, commit_sha, commit_message, status, trigger_type, trigger_branch)
VALUES (?, ?, ?, ?, ?, ?, ?)`

type CreateDeploymentParams struct {
	ID            string  `json:"id"`
	AppID         string  `json:"app_id"`
	CommitSha     string  `json:"commit_sha"`
	CommitMessage string  `json:"commit_message"`
	Status        string  `json:"status"`
	TriggerType   string  `json:"trigger_type"`
	TriggerBranch *string `json:"trigger_branch"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, createDeployment, arg.ID, arg.AppID, arg.CommitSha, arg.CommitMessage, arg.Status, arg.TriggerType, arg.TriggerBranch)
	return err
}

const updateDeploymentStatus = `UPDATE deployment SET status = ?, error = ? WHERE id = ?`

type UpdateDeploymentStatusParams struct {
	Status string  `json:"status"`
	Error  *string `json:"error"`
	ID     string  `json:"id"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentStatus, arg.Status, arg.Error, arg.ID)
	return err
}

const updateDeploymentArtifact = `UPDATE deployment SET image_tag = ?, nomad_job_hcl = ?, env_snapshot = ?, build_job_hcl = ?, pre_hook_hcl = ?, post_hook_hcl = ? WHERE id = ?`

type UpdateDeploymentArtifactParams struct {
	ImageTag    *string `json:"image_tag"`
	NomadJobHcl *string `json:"nomad_job_hcl"`
	EnvSnapshot *string `json:"env_snapshot"`
	BuildJobHcl *string `json:"build_job_hcl"`
	PreHookHcl  *string `json:"pre_hook_hcl"`
	PostHookHcl *string `json:"post_hook_hcl"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateDeploymentArtifact(ctx context.Context, arg UpdateDeploymentArtifactParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentArtifact, arg.ImageTag, arg.NomadJobHcl, arg.EnvSnapshot, arg.BuildJobHcl, arg.PreHookHcl, arg.PostHookHcl, arg.ID)
	return err
}

const finishDeployment = `UPDATE deployment SET status = ?, finished_at = CURRENT_TIMESTAMP WHERE id = ?`

type FinishDeploymentParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) FinishDeployment(ctx context.Context, arg FinishDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, finishDeployment, arg.Status, arg.ID)
	return err
}

// ── Deployment logs ──────────────────────────────────────────────────────────

const upsertDeploymentLog = `INSERT INTO deployment_log (deployment_id, phase, content)
VALUES (?, ?, ?)
ON CONFLICT(deployment_id, phase) DO UPDATE SET content = excluded.content`

type UpsertDeploymentLogParams struct {
	DeploymentID string `json:"deployment_id"`
	Phase        string `json:"phase"`
	Content      string `json:"content"`
}

func (q *Queries) UpsertDeploymentLog(ctx context.Context, arg UpsertDeploymentLogParams) error {
	_, err := q.db.ExecContext(ctx, upsertDeploymentLog, arg.DeploymentID, arg.Phase, arg.Content)
	return err
}

const getDeploymentLog = `SELECT id, deployment_id, phase, content, created_at FROM deployment_log WHERE deployment_id = ? AND phase = ?`

type GetDeploymentLogParams struct {
	DeploymentID string `json:"deployment_id"`
	Phase        string `json:"phase"`
}

func (q *Queries) GetDeploymentLog(ctx context.Context, arg GetDeploymentLogParams) (DeploymentLog, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentLog, arg.DeploymentID, arg.Phase)
	var i DeploymentLog
	err := row.Scan(&i.ID, &i.DeploymentID, &i.Phase, &i.Content, &i.CreatedAt)
	return i, err
}

// ── Users ─────────────────────────────────────────────────────────────────────

const upsertUser = `INSERT INTO users (github_id, login, email, is_admin, whitelisted)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(github_id) DO UPDATE SET login = excluded.login, email = excluded.email
RETURNING id, github_id, login, email, is_admin, whitelisted, created_at`

type UpsertUserParams struct {
	GithubID    int64   `json:"github_id"`
	Login       string  `json:"login"`
	Email       *string `json:"email"`
	IsAdmin     int64   `json:"is_admin"`
	Whitelisted int64   `json:"whitelisted"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser, arg.GithubID, arg.Login, arg.Email, arg.IsAdmin, arg.Whitelisted)
	var i User
	err := row.Scan(&i.ID, &i.GithubID, &i.Login, &i.Email, &i.IsAdmin, &i.Whitelisted, &i.CreatedAt)
	return i, err
}

const getUserByGitHubID = `SELECT id, github_id, login, email, is_admin, whitelisted, created_at FROM users WHERE github_id = ?`

func (q *Queries) GetUserByGitHubID(ctx context.Context, githubID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGitHubID, githubID)
	var i User
	err := row.Scan(&i.ID, &i.GithubID, &i.Login, &i.Email, &i.IsAdmin, &i.Whitelisted, &i.CreatedAt)
	return i, err
}

const getUserByID = `SELECT id, github_id, login, email, is_admin, whitelisted, created_at FROM users WHERE id = ?`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.GithubID, &i.Login, &i.Email, &i.IsAdmin, &i.Whitelisted, &i.CreatedAt)
	return i, err
}

const countUsers = `SELECT COUNT(*) FROM users`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listUsers = `SELECT id, github_id, login, email, is_admin, whitelisted, created_at FROM users ORDER BY created_at`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.GithubID, &i.Login, &i.Email, &i.IsAdmin, &i.Whitelisted, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const whitelistUser = `UPDATE users SET whitelisted = 1 WHERE id = ?`

func (q *Queries) WhitelistUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, whitelistUser, id)
	return err
}

// ── Sessions ──────────────────────────────────────────────────────────────────

const createSession = `INSERT INTO sessions (token, user_id, expires_at) VALUES (?, ?, ?)`

type CreateSessionParams struct {
	Token     string    `json:"token"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const getSession = `SELECT s.token, s.user_id, s.created_at, s.expires_at,
    u.id as uid, u.github_id, u.login, u.email, u.is_admin, u.whitelisted
FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.token = ? AND s.expires_at > CURRENT_TIMESTAMP`

func (q *Queries) GetSession(ctx context.Context, token string) (SessionWithUser, error) {
	row := q.db.QueryRowContext(ctx, getSession, token)
	var i SessionWithUser
	err := row.Scan(&i.Token, &i.UserID, &i.CreatedAt, &i.ExpiresAt, &i.Uid, &i.GithubID, &i.Login, &i.Email, &i.IsAdmin, &i.Whitelisted)
	return i, err
}

const deleteSession = `DELETE FROM sessions WHERE token = ?`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteExpiredSessions = `DELETE FROM sessions WHERE expires_at <= CURRENT_TIMESTAMP`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}
